auto-import openssl-0.9.6b-18 from openssl-0.9.6b-18.src.rpm

diff --git a/hobble-openssl b/hobble-openssl
--- a/hobble-openssl
+++ b/hobble-openssl
@@ -1,23 +1,29 @@
 #!/bin/sh
 
+# quit out if anything fails.
+set -e
+
 # Clean out patent-or-otherwise-encumbered code.
 # MDC-2: 4,908,861 13/03/2007
 # IDEA:  5,214,703 25/05/2010
 # RC5:   5,724,428 03/03/2015
 
-# Bah.  Assembler is hard to port.
-#(find crypto/{idea,mdc2,rc5,sha}/asm -type f | xargs -r rm -fv)
+# Remove assembler portions of IDEA, MDC2, and RC5.
 (find crypto/{idea,mdc2,rc5}/asm -type f | xargs -r rm -fv)
 
 # IDEA, MDC2 and RC5.
-for c in `find crypto/{idea,mdc2,rc5} -name "*.c" -a \! -name "*test*" -type f` ; do
+for a in idea mdc2 rc5; do
+  for c in `find crypto/$a -name "*.c" -a \! -name "*test*" -type f` ; do
+	echo Destroying $c
+	> $c
+  done
+done
+
+for c in `find crypto/evp -name "*_rc5.c" -o -name "*_idea.c" -o -name "*_mdc2.c" `; do
 	echo Destroying $c
 	> $c
 done
-for c in `find crypto/evp -name "*_r5.c" -o -name "*_i.c" -o -name "*_mdc2.c" `; do
-	echo Destroying $c
-	> $c
-done
+
 for h in `find crypto ssl apps test -name "*.h"` ; do
 	echo Removing IDEA, MDC2, and RC5 references from $h
 	cat $h | \
